# Author: KARTIK SENGAR
# SAP ID: 500083548
# ROLL NO: R214220601
# Batch: 5
# Course: Container Orchestration and Infrastructure Automation
# Program: B.TECH CSE, CC&VT


# syntax=docker/dockerfile:1
FROM python:latest

WORKDIR /app

COPY . .

CMD [ "python", "server/server.py" ]